### ISSUE TITLE
Arming is not silent

### ISSUE THREAD

**Issue by joshroseca** [schwark/smartthings-alarmcom#10]
Hello, thanks for this fantastic piece of code! Arm-Stay, Arm-Away and Disarm all appear in my app and function properly. The only issue I am having is that the arming (away or stay) is not silent. I tried adding the "adding additional variables for silent/nodelay" code and still the same result. I am using the Frontpoint basic control panel. Anyone else experienced this? Any suggestions of something to try?

**Comment by schwark** [comment]
This should work now - please try and let me know.

**Comment by adrian97c** [comment]
I can confirm works now! This issue could be closed.

**Comment by willis72** [comment]
I am still having problems with the silent arming.  I have tried toggling the setting for both "Arm Stay" and "Arm Away" and I still get the beeps when it is arming.  I did fully delete the app and reinstalled and I'm still having the same problem.

Edit:  Disregard...toggling the setting worked for me--I just failed to hit "save" after returning it to "silent".
